### PR TITLE
Add setting to enable placing in inventory when punched

### PR DESCRIPTION
**Pull request by AntumDeluge**
Adds setting `motorbike.punch_inv`:
- if enabled, bike is placed directly into inventory when punched
- default: disabled

### CODE REVIEW

**Comment by Extex101** [comment]
Good change, but instead of the settings.lua please add it to settings object in the init.lua

**Comment by AntumDeluge** [comment]
Okay, I'll get it done & update pull request.

**Comment by AntumDeluge** [comment]
Done. And I added the other settings to `settingtypes.txt`.

**Comment by AntumDeluge** [comment]
Might want to make sure that I got all the types correct in [settingtypes.txt](https://github.com/Extex101/motorbike/blob/42b5704559ae1cc7e5c95a1d07d2757add97f877/settingtypes.txt). Wasn't sure if `max_speed`, `max_reverse`, `braking`, & `crumbly_spd` were *int* types, so I used *float* to be safe (not that it would affect anything negatively as the two types are the same thing in Lua as I understand it).

**Comment by Extex101** [comment]
👍 
You want to make the setting on by default too? Then I'll quash-merge

**Comment by AntumDeluge** [comment]
> You want to make the setting on by default too?

Is that what you want? I had it off to keep the original behavior by default.

**Comment by AntumDeluge** [comment]
Done.

**Pull request merged**
