### PR TITLE
Replace Deprecated Methods

### PR DESCRIPTION
**Pull request by AntumDeluge**
- Replaces deprecated methods (`getpos` to `get_pos`, `setyaw` to `set_yaw`, etc.)
- Adds dependencies to `mod.conf`

***Edit:** <del>I'm going to make some changes to this for backward compatibility, then re-submit.</del> (done)*
- [x] keep `depends.txt`
- [x] <del>keep backward compat with `get`/`set` object methods (not sure if this can be done)</del>

***Edit:** It sounds like `getpos`, `setpos`, `setyaw`, etc. methods are so outdated that it is not worth keeping backward compat with them*

### CODE REVIEW

**Comment by AntumDeluge** [comment]
I reverted deleting `depends.txt` to keep backward compatibility.

**Comment by AntumDeluge** [comment]
I've found some more issues that I want to fix. I am going to close this & re-submit in another pull request with other fixes.

**Comment by Extex101** [comment]
Well it's minimum version is 5.0 so no need for backwards compatibility

**Comment by AntumDeluge** [comment]
<del>So, you don't want to update the deprecated `set*`/`get*` methods?</del>

Oh, oops. This is my old PR. LOL! Hard to keep track of this stuff.

**Comment by Extex101** [comment]
Well I mean about the mod.conf information

**Comment by AntumDeluge** [comment]
> Well I mean about the mod.conf information

Ah, okay.

**Pull request closed without merging**
